version: "3.0"
services:
  nginx:
    image: becongmbh/nginx:latest
    hostname: nginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - datagerry
    environment:
      NGINX_LOCATION_DEFAULT: "/;/;http://datagerry:4000"
# uncomment for ssl
#      NGINX_SSL_CERT: "/data/certs/datagerry.pem"
#      NGINX_SSL_KEY: "/data/certs/datagerry.key"
#    volumes:
#      - ./conf/ssl/certs:/data/certs
    restart: unless-stopped

  datagerry:
    image: becongmbh/datagerry:latest
    hostname: datagerry
    depends_on:
    - db
    ports:
    - 4000:4000
    environment:
      DATAGERRY_Database_host: "db"
    restart: unless-stopped

  db:
    image: mongo:6.0.25
    hostname: db
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:
